version: "3.9"

networks:
  fullcycle:
    name: fullcycle
    driver: bridge

services:
  backend:
    build: ./node
    container_name: node
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 120s -wait-retry-interval 8s ./entrypoint.sh
    ports:
      - 3333:3333
    networks:
      - fullcycle

  mysql:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysql
    tty: true
    environment:
      - MYSQL_DATABASE=fullcycle
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    networks:
      - fullcycle

  nginx:
    build:
      context: ./nginx
    ports:
      - 8080:80
    networks:
      - fullcycle
